// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange_rate.proto

package grpc.exchange;

public final class ExchangeRateOuterClass {
  private ExchangeRateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code CurrencyCode}
   */
  public enum CurrencyCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EUR = 0;</code>
     */
    EUR(0),
    /**
     * <code>USD = 1;</code>
     */
    USD(1),
    /**
     * <code>PLN = 2;</code>
     */
    PLN(2),
    /**
     * <code>CZK = 3;</code>
     */
    CZK(3),
    /**
     * <code>AUD = 4;</code>
     */
    AUD(4),
    /**
     * <code>CHF = 5;</code>
     */
    CHF(5),
    /**
     * <code>DKK = 6;</code>
     */
    DKK(6),
    /**
     * <code>GBP = 7;</code>
     */
    GBP(7),
    /**
     * <code>HRK = 8;</code>
     */
    HRK(8),
    /**
     * <code>HUF = 9;</code>
     */
    HUF(9),
    /**
     * <code>NOK = 10;</code>
     */
    NOK(10),
    /**
     * <code>RUB = 11;</code>
     */
    RUB(11),
    /**
     * <code>SEK = 12;</code>
     */
    SEK(12),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EUR = 0;</code>
     */
    public static final int EUR_VALUE = 0;
    /**
     * <code>USD = 1;</code>
     */
    public static final int USD_VALUE = 1;
    /**
     * <code>PLN = 2;</code>
     */
    public static final int PLN_VALUE = 2;
    /**
     * <code>CZK = 3;</code>
     */
    public static final int CZK_VALUE = 3;
    /**
     * <code>AUD = 4;</code>
     */
    public static final int AUD_VALUE = 4;
    /**
     * <code>CHF = 5;</code>
     */
    public static final int CHF_VALUE = 5;
    /**
     * <code>DKK = 6;</code>
     */
    public static final int DKK_VALUE = 6;
    /**
     * <code>GBP = 7;</code>
     */
    public static final int GBP_VALUE = 7;
    /**
     * <code>HRK = 8;</code>
     */
    public static final int HRK_VALUE = 8;
    /**
     * <code>HUF = 9;</code>
     */
    public static final int HUF_VALUE = 9;
    /**
     * <code>NOK = 10;</code>
     */
    public static final int NOK_VALUE = 10;
    /**
     * <code>RUB = 11;</code>
     */
    public static final int RUB_VALUE = 11;
    /**
     * <code>SEK = 12;</code>
     */
    public static final int SEK_VALUE = 12;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CurrencyCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CurrencyCode forNumber(int value) {
      switch (value) {
        case 0: return EUR;
        case 1: return USD;
        case 2: return PLN;
        case 3: return CZK;
        case 4: return AUD;
        case 5: return CHF;
        case 6: return DKK;
        case 7: return GBP;
        case 8: return HRK;
        case 9: return HUF;
        case 10: return NOK;
        case 11: return RUB;
        case 12: return SEK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CurrencyCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CurrencyCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CurrencyCode>() {
            public CurrencyCode findValueByNumber(int number) {
              return CurrencyCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.exchange.ExchangeRateOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final CurrencyCode[] VALUES = values();

    public static CurrencyCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CurrencyCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CurrencyCode)
  }

  /**
   * Protobuf enum {@code RelationOp}
   */
  public enum RelationOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GT = 0;</code>
     */
    GT(0),
    /**
     * <code>LT = 1;</code>
     */
    LT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GT = 0;</code>
     */
    public static final int GT_VALUE = 0;
    /**
     * <code>LT = 1;</code>
     */
    public static final int LT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RelationOp valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RelationOp forNumber(int value) {
      switch (value) {
        case 0: return GT;
        case 1: return LT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RelationOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RelationOp> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RelationOp>() {
            public RelationOp findValueByNumber(int number) {
              return RelationOp.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.exchange.ExchangeRateOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final RelationOp[] VALUES = values();

    public static RelationOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RelationOp(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RelationOp)
  }

  public interface CurrencyRateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CurrencyRate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CurrencyCode currencyCode = 1;</code>
     * @return The enum numeric value on the wire for currencyCode.
     */
    int getCurrencyCodeValue();
    /**
     * <code>.CurrencyCode currencyCode = 1;</code>
     * @return The currencyCode.
     */
    grpc.exchange.ExchangeRateOuterClass.CurrencyCode getCurrencyCode();

    /**
     * <code>float value = 2;</code>
     * @return The value.
     */
    float getValue();
  }
  /**
   * Protobuf type {@code CurrencyRate}
   */
  public  static final class CurrencyRate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CurrencyRate)
      CurrencyRateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrencyRate.newBuilder() to construct.
    private CurrencyRate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrencyRate() {
      currencyCode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CurrencyRate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrencyRate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              currencyCode_ = rawValue;
              break;
            }
            case 21: {

              value_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyRate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyRate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.exchange.ExchangeRateOuterClass.CurrencyRate.class, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder.class);
    }

    public static final int CURRENCYCODE_FIELD_NUMBER = 1;
    private int currencyCode_;
    /**
     * <code>.CurrencyCode currencyCode = 1;</code>
     * @return The enum numeric value on the wire for currencyCode.
     */
    public int getCurrencyCodeValue() {
      return currencyCode_;
    }
    /**
     * <code>.CurrencyCode currencyCode = 1;</code>
     * @return The currencyCode.
     */
    public grpc.exchange.ExchangeRateOuterClass.CurrencyCode getCurrencyCode() {
      @SuppressWarnings("deprecation")
      grpc.exchange.ExchangeRateOuterClass.CurrencyCode result = grpc.exchange.ExchangeRateOuterClass.CurrencyCode.valueOf(currencyCode_);
      return result == null ? grpc.exchange.ExchangeRateOuterClass.CurrencyCode.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private float value_;
    /**
     * <code>float value = 2;</code>
     * @return The value.
     */
    public float getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currencyCode_ != grpc.exchange.ExchangeRateOuterClass.CurrencyCode.EUR.getNumber()) {
        output.writeEnum(1, currencyCode_);
      }
      if (value_ != 0F) {
        output.writeFloat(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currencyCode_ != grpc.exchange.ExchangeRateOuterClass.CurrencyCode.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, currencyCode_);
      }
      if (value_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.exchange.ExchangeRateOuterClass.CurrencyRate)) {
        return super.equals(obj);
      }
      grpc.exchange.ExchangeRateOuterClass.CurrencyRate other = (grpc.exchange.ExchangeRateOuterClass.CurrencyRate) obj;

      if (currencyCode_ != other.currencyCode_) return false;
      if (java.lang.Float.floatToIntBits(getValue())
          != java.lang.Float.floatToIntBits(
              other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYCODE_FIELD_NUMBER;
      hash = (53 * hash) + currencyCode_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.exchange.ExchangeRateOuterClass.CurrencyRate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CurrencyRate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CurrencyRate)
        grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyRate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyRate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.exchange.ExchangeRateOuterClass.CurrencyRate.class, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder.class);
      }

      // Construct using grpc.exchange.ExchangeRateOuterClass.CurrencyRate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyCode_ = 0;

        value_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyRate_descriptor;
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate getDefaultInstanceForType() {
        return grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate build() {
        grpc.exchange.ExchangeRateOuterClass.CurrencyRate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate buildPartial() {
        grpc.exchange.ExchangeRateOuterClass.CurrencyRate result = new grpc.exchange.ExchangeRateOuterClass.CurrencyRate(this);
        result.currencyCode_ = currencyCode_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.exchange.ExchangeRateOuterClass.CurrencyRate) {
          return mergeFrom((grpc.exchange.ExchangeRateOuterClass.CurrencyRate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.exchange.ExchangeRateOuterClass.CurrencyRate other) {
        if (other == grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance()) return this;
        if (other.currencyCode_ != 0) {
          setCurrencyCodeValue(other.getCurrencyCodeValue());
        }
        if (other.getValue() != 0F) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.exchange.ExchangeRateOuterClass.CurrencyRate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.exchange.ExchangeRateOuterClass.CurrencyRate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int currencyCode_ = 0;
      /**
       * <code>.CurrencyCode currencyCode = 1;</code>
       * @return The enum numeric value on the wire for currencyCode.
       */
      public int getCurrencyCodeValue() {
        return currencyCode_;
      }
      /**
       * <code>.CurrencyCode currencyCode = 1;</code>
       * @param value The enum numeric value on the wire for currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCodeValue(int value) {
        currencyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CurrencyCode currencyCode = 1;</code>
       * @return The currencyCode.
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyCode getCurrencyCode() {
        @SuppressWarnings("deprecation")
        grpc.exchange.ExchangeRateOuterClass.CurrencyCode result = grpc.exchange.ExchangeRateOuterClass.CurrencyCode.valueOf(currencyCode_);
        return result == null ? grpc.exchange.ExchangeRateOuterClass.CurrencyCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.CurrencyCode currencyCode = 1;</code>
       * @param value The currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCode(grpc.exchange.ExchangeRateOuterClass.CurrencyCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currencyCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CurrencyCode currencyCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyCode() {
        
        currencyCode_ = 0;
        onChanged();
        return this;
      }

      private float value_ ;
      /**
       * <code>float value = 2;</code>
       * @return The value.
       */
      public float getValue() {
        return value_;
      }
      /**
       * <code>float value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(float value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CurrencyRate)
    }

    // @@protoc_insertion_point(class_scope:CurrencyRate)
    private static final grpc.exchange.ExchangeRateOuterClass.CurrencyRate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.exchange.ExchangeRateOuterClass.CurrencyRate();
    }

    public static grpc.exchange.ExchangeRateOuterClass.CurrencyRate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrencyRate>
        PARSER = new com.google.protobuf.AbstractParser<CurrencyRate>() {
      @java.lang.Override
      public CurrencyRate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrencyRate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrencyRate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrencyRate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.exchange.ExchangeRateOuterClass.CurrencyRate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CurrencyNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CurrencyNotification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    java.util.List<grpc.exchange.ExchangeRateOuterClass.CurrencyRate> 
        getCurrencyRateList();
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    grpc.exchange.ExchangeRateOuterClass.CurrencyRate getCurrencyRate(int index);
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    int getCurrencyRateCount();
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    java.util.List<? extends grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> 
        getCurrencyRateOrBuilderList();
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder getCurrencyRateOrBuilder(
        int index);

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code CurrencyNotification}
   */
  public  static final class CurrencyNotification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CurrencyNotification)
      CurrencyNotificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrencyNotification.newBuilder() to construct.
    private CurrencyNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrencyNotification() {
      currencyRate_ = java.util.Collections.emptyList();
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CurrencyNotification();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrencyNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                currencyRate_ = new java.util.ArrayList<grpc.exchange.ExchangeRateOuterClass.CurrencyRate>();
                mutable_bitField0_ |= 0x00000001;
              }
              currencyRate_.add(
                  input.readMessage(grpc.exchange.ExchangeRateOuterClass.CurrencyRate.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          currencyRate_ = java.util.Collections.unmodifiableList(currencyRate_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyNotification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.class, grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.Builder.class);
    }

    public static final int CURRENCYRATE_FIELD_NUMBER = 1;
    private java.util.List<grpc.exchange.ExchangeRateOuterClass.CurrencyRate> currencyRate_;
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    public java.util.List<grpc.exchange.ExchangeRateOuterClass.CurrencyRate> getCurrencyRateList() {
      return currencyRate_;
    }
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    public java.util.List<? extends grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> 
        getCurrencyRateOrBuilderList() {
      return currencyRate_;
    }
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    public int getCurrencyRateCount() {
      return currencyRate_.size();
    }
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    public grpc.exchange.ExchangeRateOuterClass.CurrencyRate getCurrencyRate(int index) {
      return currencyRate_.get(index);
    }
    /**
     * <code>repeated .CurrencyRate currencyRate = 1;</code>
     */
    public grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder getCurrencyRateOrBuilder(
        int index) {
      return currencyRate_.get(index);
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < currencyRate_.size(); i++) {
        output.writeMessage(1, currencyRate_.get(i));
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < currencyRate_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, currencyRate_.get(i));
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.exchange.ExchangeRateOuterClass.CurrencyNotification)) {
        return super.equals(obj);
      }
      grpc.exchange.ExchangeRateOuterClass.CurrencyNotification other = (grpc.exchange.ExchangeRateOuterClass.CurrencyNotification) obj;

      if (!getCurrencyRateList()
          .equals(other.getCurrencyRateList())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCurrencyRateCount() > 0) {
        hash = (37 * hash) + CURRENCYRATE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrencyRateList().hashCode();
      }
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.exchange.ExchangeRateOuterClass.CurrencyNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CurrencyNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CurrencyNotification)
        grpc.exchange.ExchangeRateOuterClass.CurrencyNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyNotification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.class, grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.Builder.class);
      }

      // Construct using grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCurrencyRateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (currencyRateBuilder_ == null) {
          currencyRate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          currencyRateBuilder_.clear();
        }
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_CurrencyNotification_descriptor;
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.CurrencyNotification getDefaultInstanceForType() {
        return grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.CurrencyNotification build() {
        grpc.exchange.ExchangeRateOuterClass.CurrencyNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.CurrencyNotification buildPartial() {
        grpc.exchange.ExchangeRateOuterClass.CurrencyNotification result = new grpc.exchange.ExchangeRateOuterClass.CurrencyNotification(this);
        int from_bitField0_ = bitField0_;
        if (currencyRateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            currencyRate_ = java.util.Collections.unmodifiableList(currencyRate_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.currencyRate_ = currencyRate_;
        } else {
          result.currencyRate_ = currencyRateBuilder_.build();
        }
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.exchange.ExchangeRateOuterClass.CurrencyNotification) {
          return mergeFrom((grpc.exchange.ExchangeRateOuterClass.CurrencyNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.exchange.ExchangeRateOuterClass.CurrencyNotification other) {
        if (other == grpc.exchange.ExchangeRateOuterClass.CurrencyNotification.getDefaultInstance()) return this;
        if (currencyRateBuilder_ == null) {
          if (!other.currencyRate_.isEmpty()) {
            if (currencyRate_.isEmpty()) {
              currencyRate_ = other.currencyRate_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCurrencyRateIsMutable();
              currencyRate_.addAll(other.currencyRate_);
            }
            onChanged();
          }
        } else {
          if (!other.currencyRate_.isEmpty()) {
            if (currencyRateBuilder_.isEmpty()) {
              currencyRateBuilder_.dispose();
              currencyRateBuilder_ = null;
              currencyRate_ = other.currencyRate_;
              bitField0_ = (bitField0_ & ~0x00000001);
              currencyRateBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCurrencyRateFieldBuilder() : null;
            } else {
              currencyRateBuilder_.addAllMessages(other.currencyRate_);
            }
          }
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.exchange.ExchangeRateOuterClass.CurrencyNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.exchange.ExchangeRateOuterClass.CurrencyNotification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<grpc.exchange.ExchangeRateOuterClass.CurrencyRate> currencyRate_ =
        java.util.Collections.emptyList();
      private void ensureCurrencyRateIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          currencyRate_ = new java.util.ArrayList<grpc.exchange.ExchangeRateOuterClass.CurrencyRate>(currencyRate_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.exchange.ExchangeRateOuterClass.CurrencyRate, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder, grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> currencyRateBuilder_;

      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public java.util.List<grpc.exchange.ExchangeRateOuterClass.CurrencyRate> getCurrencyRateList() {
        if (currencyRateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(currencyRate_);
        } else {
          return currencyRateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public int getCurrencyRateCount() {
        if (currencyRateBuilder_ == null) {
          return currencyRate_.size();
        } else {
          return currencyRateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate getCurrencyRate(int index) {
        if (currencyRateBuilder_ == null) {
          return currencyRate_.get(index);
        } else {
          return currencyRateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder setCurrencyRate(
          int index, grpc.exchange.ExchangeRateOuterClass.CurrencyRate value) {
        if (currencyRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrencyRateIsMutable();
          currencyRate_.set(index, value);
          onChanged();
        } else {
          currencyRateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder setCurrencyRate(
          int index, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder builderForValue) {
        if (currencyRateBuilder_ == null) {
          ensureCurrencyRateIsMutable();
          currencyRate_.set(index, builderForValue.build());
          onChanged();
        } else {
          currencyRateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder addCurrencyRate(grpc.exchange.ExchangeRateOuterClass.CurrencyRate value) {
        if (currencyRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrencyRateIsMutable();
          currencyRate_.add(value);
          onChanged();
        } else {
          currencyRateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder addCurrencyRate(
          int index, grpc.exchange.ExchangeRateOuterClass.CurrencyRate value) {
        if (currencyRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrencyRateIsMutable();
          currencyRate_.add(index, value);
          onChanged();
        } else {
          currencyRateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder addCurrencyRate(
          grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder builderForValue) {
        if (currencyRateBuilder_ == null) {
          ensureCurrencyRateIsMutable();
          currencyRate_.add(builderForValue.build());
          onChanged();
        } else {
          currencyRateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder addCurrencyRate(
          int index, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder builderForValue) {
        if (currencyRateBuilder_ == null) {
          ensureCurrencyRateIsMutable();
          currencyRate_.add(index, builderForValue.build());
          onChanged();
        } else {
          currencyRateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder addAllCurrencyRate(
          java.lang.Iterable<? extends grpc.exchange.ExchangeRateOuterClass.CurrencyRate> values) {
        if (currencyRateBuilder_ == null) {
          ensureCurrencyRateIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, currencyRate_);
          onChanged();
        } else {
          currencyRateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder clearCurrencyRate() {
        if (currencyRateBuilder_ == null) {
          currencyRate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          currencyRateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public Builder removeCurrencyRate(int index) {
        if (currencyRateBuilder_ == null) {
          ensureCurrencyRateIsMutable();
          currencyRate_.remove(index);
          onChanged();
        } else {
          currencyRateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder getCurrencyRateBuilder(
          int index) {
        return getCurrencyRateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder getCurrencyRateOrBuilder(
          int index) {
        if (currencyRateBuilder_ == null) {
          return currencyRate_.get(index);  } else {
          return currencyRateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public java.util.List<? extends grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> 
           getCurrencyRateOrBuilderList() {
        if (currencyRateBuilder_ != null) {
          return currencyRateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(currencyRate_);
        }
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder addCurrencyRateBuilder() {
        return getCurrencyRateFieldBuilder().addBuilder(
            grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance());
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder addCurrencyRateBuilder(
          int index) {
        return getCurrencyRateFieldBuilder().addBuilder(
            index, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance());
      }
      /**
       * <code>repeated .CurrencyRate currencyRate = 1;</code>
       */
      public java.util.List<grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder> 
           getCurrencyRateBuilderList() {
        return getCurrencyRateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          grpc.exchange.ExchangeRateOuterClass.CurrencyRate, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder, grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> 
          getCurrencyRateFieldBuilder() {
        if (currencyRateBuilder_ == null) {
          currencyRateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              grpc.exchange.ExchangeRateOuterClass.CurrencyRate, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder, grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder>(
                  currencyRate_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          currencyRate_ = null;
        }
        return currencyRateBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CurrencyNotification)
    }

    // @@protoc_insertion_point(class_scope:CurrencyNotification)
    private static final grpc.exchange.ExchangeRateOuterClass.CurrencyNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.exchange.ExchangeRateOuterClass.CurrencyNotification();
    }

    public static grpc.exchange.ExchangeRateOuterClass.CurrencyNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrencyNotification>
        PARSER = new com.google.protobuf.AbstractParser<CurrencyNotification>() {
      @java.lang.Override
      public CurrencyNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrencyNotification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrencyNotification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrencyNotification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.exchange.ExchangeRateOuterClass.CurrencyNotification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConditionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Condition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RelationOp relationOp = 1;</code>
     * @return The enum numeric value on the wire for relationOp.
     */
    int getRelationOpValue();
    /**
     * <code>.RelationOp relationOp = 1;</code>
     * @return The relationOp.
     */
    grpc.exchange.ExchangeRateOuterClass.RelationOp getRelationOp();

    /**
     * <code>.CurrencyRate currencyRate = 2;</code>
     * @return Whether the currencyRate field is set.
     */
    boolean hasCurrencyRate();
    /**
     * <code>.CurrencyRate currencyRate = 2;</code>
     * @return The currencyRate.
     */
    grpc.exchange.ExchangeRateOuterClass.CurrencyRate getCurrencyRate();
    /**
     * <code>.CurrencyRate currencyRate = 2;</code>
     */
    grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder getCurrencyRateOrBuilder();
  }
  /**
   * Protobuf type {@code Condition}
   */
  public  static final class Condition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Condition)
      ConditionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Condition.newBuilder() to construct.
    private Condition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Condition() {
      relationOp_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Condition();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Condition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              relationOp_ = rawValue;
              break;
            }
            case 18: {
              grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder subBuilder = null;
              if (currencyRate_ != null) {
                subBuilder = currencyRate_.toBuilder();
              }
              currencyRate_ = input.readMessage(grpc.exchange.ExchangeRateOuterClass.CurrencyRate.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(currencyRate_);
                currencyRate_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.exchange.ExchangeRateOuterClass.internal_static_Condition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.exchange.ExchangeRateOuterClass.internal_static_Condition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.exchange.ExchangeRateOuterClass.Condition.class, grpc.exchange.ExchangeRateOuterClass.Condition.Builder.class);
    }

    public static final int RELATIONOP_FIELD_NUMBER = 1;
    private int relationOp_;
    /**
     * <code>.RelationOp relationOp = 1;</code>
     * @return The enum numeric value on the wire for relationOp.
     */
    public int getRelationOpValue() {
      return relationOp_;
    }
    /**
     * <code>.RelationOp relationOp = 1;</code>
     * @return The relationOp.
     */
    public grpc.exchange.ExchangeRateOuterClass.RelationOp getRelationOp() {
      @SuppressWarnings("deprecation")
      grpc.exchange.ExchangeRateOuterClass.RelationOp result = grpc.exchange.ExchangeRateOuterClass.RelationOp.valueOf(relationOp_);
      return result == null ? grpc.exchange.ExchangeRateOuterClass.RelationOp.UNRECOGNIZED : result;
    }

    public static final int CURRENCYRATE_FIELD_NUMBER = 2;
    private grpc.exchange.ExchangeRateOuterClass.CurrencyRate currencyRate_;
    /**
     * <code>.CurrencyRate currencyRate = 2;</code>
     * @return Whether the currencyRate field is set.
     */
    public boolean hasCurrencyRate() {
      return currencyRate_ != null;
    }
    /**
     * <code>.CurrencyRate currencyRate = 2;</code>
     * @return The currencyRate.
     */
    public grpc.exchange.ExchangeRateOuterClass.CurrencyRate getCurrencyRate() {
      return currencyRate_ == null ? grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance() : currencyRate_;
    }
    /**
     * <code>.CurrencyRate currencyRate = 2;</code>
     */
    public grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder getCurrencyRateOrBuilder() {
      return getCurrencyRate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (relationOp_ != grpc.exchange.ExchangeRateOuterClass.RelationOp.GT.getNumber()) {
        output.writeEnum(1, relationOp_);
      }
      if (currencyRate_ != null) {
        output.writeMessage(2, getCurrencyRate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (relationOp_ != grpc.exchange.ExchangeRateOuterClass.RelationOp.GT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, relationOp_);
      }
      if (currencyRate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCurrencyRate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.exchange.ExchangeRateOuterClass.Condition)) {
        return super.equals(obj);
      }
      grpc.exchange.ExchangeRateOuterClass.Condition other = (grpc.exchange.ExchangeRateOuterClass.Condition) obj;

      if (relationOp_ != other.relationOp_) return false;
      if (hasCurrencyRate() != other.hasCurrencyRate()) return false;
      if (hasCurrencyRate()) {
        if (!getCurrencyRate()
            .equals(other.getCurrencyRate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RELATIONOP_FIELD_NUMBER;
      hash = (53 * hash) + relationOp_;
      if (hasCurrencyRate()) {
        hash = (37 * hash) + CURRENCYRATE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrencyRate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.exchange.ExchangeRateOuterClass.Condition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.exchange.ExchangeRateOuterClass.Condition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Condition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Condition)
        grpc.exchange.ExchangeRateOuterClass.ConditionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_Condition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_Condition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.exchange.ExchangeRateOuterClass.Condition.class, grpc.exchange.ExchangeRateOuterClass.Condition.Builder.class);
      }

      // Construct using grpc.exchange.ExchangeRateOuterClass.Condition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        relationOp_ = 0;

        if (currencyRateBuilder_ == null) {
          currencyRate_ = null;
        } else {
          currencyRate_ = null;
          currencyRateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.exchange.ExchangeRateOuterClass.internal_static_Condition_descriptor;
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.Condition getDefaultInstanceForType() {
        return grpc.exchange.ExchangeRateOuterClass.Condition.getDefaultInstance();
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.Condition build() {
        grpc.exchange.ExchangeRateOuterClass.Condition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc.exchange.ExchangeRateOuterClass.Condition buildPartial() {
        grpc.exchange.ExchangeRateOuterClass.Condition result = new grpc.exchange.ExchangeRateOuterClass.Condition(this);
        result.relationOp_ = relationOp_;
        if (currencyRateBuilder_ == null) {
          result.currencyRate_ = currencyRate_;
        } else {
          result.currencyRate_ = currencyRateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.exchange.ExchangeRateOuterClass.Condition) {
          return mergeFrom((grpc.exchange.ExchangeRateOuterClass.Condition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.exchange.ExchangeRateOuterClass.Condition other) {
        if (other == grpc.exchange.ExchangeRateOuterClass.Condition.getDefaultInstance()) return this;
        if (other.relationOp_ != 0) {
          setRelationOpValue(other.getRelationOpValue());
        }
        if (other.hasCurrencyRate()) {
          mergeCurrencyRate(other.getCurrencyRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.exchange.ExchangeRateOuterClass.Condition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.exchange.ExchangeRateOuterClass.Condition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int relationOp_ = 0;
      /**
       * <code>.RelationOp relationOp = 1;</code>
       * @return The enum numeric value on the wire for relationOp.
       */
      public int getRelationOpValue() {
        return relationOp_;
      }
      /**
       * <code>.RelationOp relationOp = 1;</code>
       * @param value The enum numeric value on the wire for relationOp to set.
       * @return This builder for chaining.
       */
      public Builder setRelationOpValue(int value) {
        relationOp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RelationOp relationOp = 1;</code>
       * @return The relationOp.
       */
      public grpc.exchange.ExchangeRateOuterClass.RelationOp getRelationOp() {
        @SuppressWarnings("deprecation")
        grpc.exchange.ExchangeRateOuterClass.RelationOp result = grpc.exchange.ExchangeRateOuterClass.RelationOp.valueOf(relationOp_);
        return result == null ? grpc.exchange.ExchangeRateOuterClass.RelationOp.UNRECOGNIZED : result;
      }
      /**
       * <code>.RelationOp relationOp = 1;</code>
       * @param value The relationOp to set.
       * @return This builder for chaining.
       */
      public Builder setRelationOp(grpc.exchange.ExchangeRateOuterClass.RelationOp value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        relationOp_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RelationOp relationOp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRelationOp() {
        
        relationOp_ = 0;
        onChanged();
        return this;
      }

      private grpc.exchange.ExchangeRateOuterClass.CurrencyRate currencyRate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.exchange.ExchangeRateOuterClass.CurrencyRate, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder, grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> currencyRateBuilder_;
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       * @return Whether the currencyRate field is set.
       */
      public boolean hasCurrencyRate() {
        return currencyRateBuilder_ != null || currencyRate_ != null;
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       * @return The currencyRate.
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate getCurrencyRate() {
        if (currencyRateBuilder_ == null) {
          return currencyRate_ == null ? grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance() : currencyRate_;
        } else {
          return currencyRateBuilder_.getMessage();
        }
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      public Builder setCurrencyRate(grpc.exchange.ExchangeRateOuterClass.CurrencyRate value) {
        if (currencyRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          currencyRate_ = value;
          onChanged();
        } else {
          currencyRateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      public Builder setCurrencyRate(
          grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder builderForValue) {
        if (currencyRateBuilder_ == null) {
          currencyRate_ = builderForValue.build();
          onChanged();
        } else {
          currencyRateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      public Builder mergeCurrencyRate(grpc.exchange.ExchangeRateOuterClass.CurrencyRate value) {
        if (currencyRateBuilder_ == null) {
          if (currencyRate_ != null) {
            currencyRate_ =
              grpc.exchange.ExchangeRateOuterClass.CurrencyRate.newBuilder(currencyRate_).mergeFrom(value).buildPartial();
          } else {
            currencyRate_ = value;
          }
          onChanged();
        } else {
          currencyRateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      public Builder clearCurrencyRate() {
        if (currencyRateBuilder_ == null) {
          currencyRate_ = null;
          onChanged();
        } else {
          currencyRate_ = null;
          currencyRateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder getCurrencyRateBuilder() {
        
        onChanged();
        return getCurrencyRateFieldBuilder().getBuilder();
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      public grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder getCurrencyRateOrBuilder() {
        if (currencyRateBuilder_ != null) {
          return currencyRateBuilder_.getMessageOrBuilder();
        } else {
          return currencyRate_ == null ?
              grpc.exchange.ExchangeRateOuterClass.CurrencyRate.getDefaultInstance() : currencyRate_;
        }
      }
      /**
       * <code>.CurrencyRate currencyRate = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc.exchange.ExchangeRateOuterClass.CurrencyRate, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder, grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder> 
          getCurrencyRateFieldBuilder() {
        if (currencyRateBuilder_ == null) {
          currencyRateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc.exchange.ExchangeRateOuterClass.CurrencyRate, grpc.exchange.ExchangeRateOuterClass.CurrencyRate.Builder, grpc.exchange.ExchangeRateOuterClass.CurrencyRateOrBuilder>(
                  getCurrencyRate(),
                  getParentForChildren(),
                  isClean());
          currencyRate_ = null;
        }
        return currencyRateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Condition)
    }

    // @@protoc_insertion_point(class_scope:Condition)
    private static final grpc.exchange.ExchangeRateOuterClass.Condition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.exchange.ExchangeRateOuterClass.Condition();
    }

    public static grpc.exchange.ExchangeRateOuterClass.Condition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Condition>
        PARSER = new com.google.protobuf.AbstractParser<Condition>() {
      @java.lang.Override
      public Condition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Condition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Condition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Condition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc.exchange.ExchangeRateOuterClass.Condition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyRate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyRate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyNotification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyNotification_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Condition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Condition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023exchange_rate.proto\"B\n\014CurrencyRate\022#\n" +
      "\014currencyCode\030\001 \001(\0162\r.CurrencyCode\022\r\n\005va" +
      "lue\030\002 \001(\002\"L\n\024CurrencyNotification\022#\n\014cur" +
      "rencyRate\030\001 \003(\0132\r.CurrencyRate\022\017\n\007messag" +
      "e\030\002 \001(\t\"Q\n\tCondition\022\037\n\nrelationOp\030\001 \001(\016" +
      "2\013.RelationOp\022#\n\014currencyRate\030\002 \001(\0132\r.Cu" +
      "rrencyRate*\203\001\n\014CurrencyCode\022\007\n\003EUR\020\000\022\007\n\003" +
      "USD\020\001\022\007\n\003PLN\020\002\022\007\n\003CZK\020\003\022\007\n\003AUD\020\004\022\007\n\003CHF\020" +
      "\005\022\007\n\003DKK\020\006\022\007\n\003GBP\020\007\022\007\n\003HRK\020\010\022\007\n\003HUF\020\t\022\007\n" +
      "\003NOK\020\n\022\007\n\003RUB\020\013\022\007\n\003SEK\020\014*\034\n\nRelationOp\022\006" +
      "\n\002GT\020\000\022\006\n\002LT\020\0012@\n\014ExchangeRate\0220\n\tSubscr" +
      "ibe\022\n.Condition\032\025.CurrencyNotification0\001" +
      "B\017\n\rgrpc.exchangeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CurrencyRate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CurrencyRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyRate_descriptor,
        new java.lang.String[] { "CurrencyCode", "Value", });
    internal_static_CurrencyNotification_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CurrencyNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyNotification_descriptor,
        new java.lang.String[] { "CurrencyRate", "Message", });
    internal_static_Condition_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Condition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Condition_descriptor,
        new java.lang.String[] { "RelationOp", "CurrencyRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
