# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_rate.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange_rate.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\rgrpc.exchange',
  serialized_pb=b'\n\x13\x65xchange_rate.proto\"B\n\x0c\x43urrencyRate\x12#\n\x0c\x63urrencyCode\x18\x01 \x01(\x0e\x32\r.CurrencyCode\x12\r\n\x05value\x18\x02 \x01(\x02\"L\n\x14\x43urrencyNotification\x12#\n\x0c\x63urrencyRate\x18\x01 \x03(\x0b\x32\r.CurrencyRate\x12\x0f\n\x07message\x18\x02 \x01(\t\"Q\n\tCondition\x12\x1f\n\nrelationOp\x18\x01 \x01(\x0e\x32\x0b.RelationOp\x12#\n\x0c\x63urrencyRate\x18\x02 \x01(\x0b\x32\r.CurrencyRate*\x83\x01\n\x0c\x43urrencyCode\x12\x07\n\x03\x45UR\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03PLN\x10\x02\x12\x07\n\x03\x43ZK\x10\x03\x12\x07\n\x03\x41UD\x10\x04\x12\x07\n\x03\x43HF\x10\x05\x12\x07\n\x03\x44KK\x10\x06\x12\x07\n\x03GBP\x10\x07\x12\x07\n\x03HRK\x10\x08\x12\x07\n\x03HUF\x10\t\x12\x07\n\x03NOK\x10\n\x12\x07\n\x03RUB\x10\x0b\x12\x07\n\x03SEK\x10\x0c*\x1c\n\nRelationOp\x12\x06\n\x02GT\x10\x00\x12\x06\n\x02LT\x10\x01\x32@\n\x0c\x45xchangeRate\x12\x30\n\tSubscribe\x12\n.Condition\x1a\x15.CurrencyNotification0\x01\x42\x0f\n\rgrpc.exchangeb\x06proto3'
)

_CURRENCYCODE = _descriptor.EnumDescriptor(
  name='CurrencyCode',
  full_name='CurrencyCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EUR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CZK', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUD', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DKK', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GBP', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HRK', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HUF', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOK', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUB', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEK', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=253,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_CURRENCYCODE)

CurrencyCode = enum_type_wrapper.EnumTypeWrapper(_CURRENCYCODE)
_RELATIONOP = _descriptor.EnumDescriptor(
  name='RelationOp',
  full_name='RelationOp',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=386,
  serialized_end=414,
)
_sym_db.RegisterEnumDescriptor(_RELATIONOP)

RelationOp = enum_type_wrapper.EnumTypeWrapper(_RELATIONOP)
EUR = 0
USD = 1
PLN = 2
CZK = 3
AUD = 4
CHF = 5
DKK = 6
GBP = 7
HRK = 8
HUF = 9
NOK = 10
RUB = 11
SEK = 12
GT = 0
LT = 1



_CURRENCYRATE = _descriptor.Descriptor(
  name='CurrencyRate',
  full_name='CurrencyRate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currencyCode', full_name='CurrencyRate.currencyCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CurrencyRate.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=89,
)


_CURRENCYNOTIFICATION = _descriptor.Descriptor(
  name='CurrencyNotification',
  full_name='CurrencyNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currencyRate', full_name='CurrencyNotification.currencyRate', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='CurrencyNotification.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=167,
)


_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='relationOp', full_name='Condition.relationOp', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currencyRate', full_name='Condition.currencyRate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=250,
)

_CURRENCYRATE.fields_by_name['currencyCode'].enum_type = _CURRENCYCODE
_CURRENCYNOTIFICATION.fields_by_name['currencyRate'].message_type = _CURRENCYRATE
_CONDITION.fields_by_name['relationOp'].enum_type = _RELATIONOP
_CONDITION.fields_by_name['currencyRate'].message_type = _CURRENCYRATE
DESCRIPTOR.message_types_by_name['CurrencyRate'] = _CURRENCYRATE
DESCRIPTOR.message_types_by_name['CurrencyNotification'] = _CURRENCYNOTIFICATION
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
DESCRIPTOR.enum_types_by_name['CurrencyCode'] = _CURRENCYCODE
DESCRIPTOR.enum_types_by_name['RelationOp'] = _RELATIONOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurrencyRate = _reflection.GeneratedProtocolMessageType('CurrencyRate', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYRATE,
  '__module__' : 'exchange_rate_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyRate)
  })
_sym_db.RegisterMessage(CurrencyRate)

CurrencyNotification = _reflection.GeneratedProtocolMessageType('CurrencyNotification', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYNOTIFICATION,
  '__module__' : 'exchange_rate_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyNotification)
  })
_sym_db.RegisterMessage(CurrencyNotification)

Condition = _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), {
  'DESCRIPTOR' : _CONDITION,
  '__module__' : 'exchange_rate_pb2'
  # @@protoc_insertion_point(class_scope:Condition)
  })
_sym_db.RegisterMessage(Condition)


DESCRIPTOR._options = None

_EXCHANGERATE = _descriptor.ServiceDescriptor(
  name='ExchangeRate',
  full_name='ExchangeRate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=416,
  serialized_end=480,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='ExchangeRate.Subscribe',
    index=0,
    containing_service=None,
    input_type=_CONDITION,
    output_type=_CURRENCYNOTIFICATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXCHANGERATE)

DESCRIPTOR.services_by_name['ExchangeRate'] = _EXCHANGERATE

# @@protoc_insertion_point(module_scope)
